version: '3'
services:
    user-hub:
      image: fonzeca/user-hub:dev
      ports:
        - 5623:5623
      networks:
        - carmind
      extra_hosts:
        - mongoservice:172.21.0.1
      volumes:
        - ./../config/user-hub/config.json:/user-hub/config.json

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true
