name: Main Workflow

on:
  push:
    branches:
        - dev
      
jobs:
  deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      main_tag: $GITHUB_REF_NAME

  reload_compose:
    needs: deployment
    secrets: inherit
    uses: ./.github/workflows/reload_compose.yml
